### ISSUE TITLE
Dataset download link is down

### ISSUE THREAD

**Issue by gizatt** [mdfirman/voxlets#1]
Current link to the Dropbox-hosted dataset is down -- could you update that link?

**Comment by stepByStepToSky** [comment]
@gizatt @mdfirman @macaodha  I find the same problem that the link do not work. I try to ping it,  I also get error. I can use google accessibly. So can you update the link, I would be  sincerely appreciate for your help.

**Comment by HectorAnadon** [comment]
I would be interested in the dataset too.

**Comment by Mids** [comment]
Is there anyone got the link or have any other datasets?

**Comment by mdfirman** [comment]
Hi all, sorry for the delay - I had to re-carve the voxel volumes.

68e63b5143c52c84fefb583d0060013bdbebabe5 should have fixed this, so the links in the README are now fixed. Let me know if there are any remaining problems. Thanks

**Comment by Mids** [comment]
Hi

First of all, thank you for your fix, but when I tried to run your code,
"05_voxel_carving", it requires more files than I got.
No such file or directory:
'/media/michael/Seagate/phd_projects/volume_completion_data/data/oisin_house/data/saved_00209/poses.yaml'
I changed every paths relative, but I couldn't find this file in your
project.
Would you please look up your computer and upload those?
